### ISSUE TITLE
Isolated mazes

### ISSUE THREAD

**Issue by Synoecium** [Rhiba/cpp-cave-gen#1]
I tried this code and got maze wigh isolated mazes. Should you advise how to change algorithm to get fully connected labirinth?

**Comment by Rhiba** [comment]
Hey! So it's completely random whether the caves (sidenote: this is not a maze algorithm, it's for cave-like structures!) will join up or not, but with some post-processing, I'm sure you could connect all areas! Here's some pseudo-code for a naive algorithm that will connect all chambers:

- pick a random empty "air" cell
- flood fill from that cell and label all connecting to it with a 1 (and remove from the set of air cells)
- pick another random empty "air" cell
- flood fill from that cell and label all connecting to it with a 2 (and remove from the set of air cells)
- repeat until all cells that were originally "air" are labelled with a number
- connect different numbered chambers by searching for the shortest distance (in number of cells) between two different numbers (up to you how to implement but a brute force search would work on small areas like the default set in this code) and setting the connecting cells to be the number label of one of the two chambers
- flood fill the newly connected areas with one label (the same label you picked to be the label of the connecting cells)
- repeat until only one number label exists, then they're all connected

**Comment by Synoecium** [comment]
Excuse me, i thought "cave" means maze with caves generation. Thanks for describing connection algorithm, i should try it, cause i didnt found working c++ code for maze-with-caves generation.
